Prepare for 11.0.9 EA builds cycle
AdoptOpenJDK/openjdk11-upstream-binaries pull request #8
Opened 2020-07-20 07:21 UTC by jhuttana

Could you please review the changes?

2020-07-20 13:45 UTC, jerboaa requested changes

2020-07-20 13:45 UTC, jerboaa commented on install-rhel-deps-build-openjdk11.sh
> +BOOT_JDK="/opt/openjdk-11.0.8+10/"
Have you tried this? AFAIK, folder names now are `openjdk-11.0.8_10` NOT `openjdk-11.0.8+10`.

2020-07-20 14:19 UTC, jhuttana commented on install-rhel-deps-build-openjdk11.sh
> +BOOT_JDK="/opt/openjdk-11.0.8+10/"
You are right :) It was my mistake ;) Now I have addressed the review comment.
Could you please take a look?

2020-07-20 14:37 UTC, jerboaa reviewed
LGTM. Like JDK 8, we should only merge once 11.0.9+1 has been tagged upstream.

2020-07-20 14:40 UTC, jhuttana commented
> LGTM. Like JDK 8, we should only merge once 11.0.9+1 has been tagged upstream.

Sure. Thank you!

2020-07-29 10:06 UTC, jerboaa approved these changes
LGTM

2020-07-29 10:07 UTC, merged